language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer    # https://github.com/travis-ci/travis-ci/issues/3259
script:
  - mvn test -B -Dmatsim.preferLocalDtds=true
  - if [[ $TRAVIS_BRANCH == "releases" ]]; then if [[ $( cat pom.xml | grep SNAPSHOT ) ]]; then exit 1; else mvn deploy -DskipTests=true --settings=settings.xml; fi; fi
env:
  global:
    - MAVEN_OPTS="-Xmx2g"
cache:
  directories:
  - $HOME/.m2
